### PR TITLE
Admin UI: List Identities in the Client Details page

### PR DESCRIPTION
**Pull request by JLSRKonk**
# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

# Screenshots
## Client Details
image
_note: Created with Client column and filter not shown in the Client Details page_

## List Identities
image
_note: Created with Client column and filter are shown in the List Identities page_

### CODE REVIEW

**Comment by daniel-almeida-konkconsulting** [comment]
Can we center the table content with the filters?
I think it would look a lot cleaner in both pages.
A simples `text-align: center` should be sufficient.

**Comment by daniel-almeida-konkconsulting** [comment]
From the screenshots, it appears the table (when in the identity overview page) is not occupying the page in its entirety.
Wasn't this the case before promoting it to a separate component?
I'd say we need as much screen real estate as we have available for this page.

**Comment by JLSRKonk** [comment]
> Can we center the table content with the filters? I think it would look a lot cleaner in both pages. A simple `text-align: center` should be sufficient.

Here is a screenshot with the text centered:
image
@tnotheis Do you prefer the table content to be centered, or should we leave it as it was before?



> From the screenshots, it appears the table (when in the identity overview page) is not occupying the page in its entirety. Wasn't this the case before promoting it to a separate component? I'd say we need as much screen real estate as we have available for this page.

For the screenshots, I zoomed out the page to 50%, so maybe that is why the width may look a bit odd.
I tested it in the main branch and it looks the same, so the width should still be the same as before.
For reference, here is a normal 100% zoom screenshot:
image
There is a scrollbar below for the rest of the table.

**Comment by tnotheis** [comment]
I kind of dislike both. ;) But since I don't have a better idea, let's go with the centered approach.

**Review by tnotheis — APPROVED** [review]

**Pull request merged**
