### PR TITLE
Migrate to new solution format

### PR DESCRIPTION
**Pull request by tnotheis**
# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

This PR removes the old solution file, with the old format (`.sln` extension) and adds one with the new format (`.slnx`), which is a million times easier to read (see https://medium.com/c-sharp-programming/a-closer-look-at-visual-studios-new-slnx-file-format-521e15a20e96 for a brief description).

I'm not sure if Visual Studio officialy supports the new format already. That's why I would like one of you to test it (I'm currently on my laptop, which doesn't have VS installed). Make sure to update to the latest Version of VS before you test it.

Let me know if it works in a comment. And if it works, approve the PR.

Thanks.

### CODE REVIEW

**Comment by tnotheis** [comment]
Mhh, okay, nvm. Seems like the dotnet CLI doesn't have support for the new format, yet...

**Comment by ericbrunner** [comment]
` .slnx`  not recognized as a valid solition in Visual Studio Version `17.11.5`

**Comment by tnotheis** [comment]
It's funny that Rider introduces official support for the new solution type before Microsoft themselves do. 😆

**Comment by ericbrunner** [comment]
> It's funny that Rider introduces official support for the new solution type before Microsoft themselves do. 😆

Seems like that is still in devlopement on the MS Build team side:
image
https://blog.jetbrains.com/dotnet/2024/10/04/support-for-slnx-solution-files/

**Comment by tnotheis** [comment]
Yeah. As long as this isn't fully supported, we shouldn't migrate to the new solution. Keeping those file in sync would be a pain.

**Pull request closed without merging**
