### PR TITLE
Limit content width of Admin UI

### PR DESCRIPTION
**Pull request by JLSRKonk**
# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

### CODE REVIEW

**Comment by JLSRKonk** [comment]
**Screenshots Widescreen**

Screenshot 2023-08-11 113437

Screenshot 2023-08-11 113454

Screenshot 2023-08-11 113513

Screenshot 2023-08-11 113530

Screenshot 2023-08-11 113546

Screenshot 2023-08-11 113602

Screenshot 2023-08-11 113617

Screenshot 2023-08-11 113639

Screenshot 2023-08-11 113659

Screenshot 2023-08-11 113727

Screenshot 2023-08-11 113740

Screenshot 2023-08-11 113753

**Comment by tnotheis** [comment]
1. How wide would you have to make the content area to fit the column names of the Identities table on one row?
2. Is it hard to center the dialogs based on the actual content area and not the whole screen? Right now they look a little off.

**Review by tnotheis — CHANGES_REQUESTED** [review]
See above

**Comment by JLSRKonk** [comment]
> 1. How wide would you have to make the content area to fit the column names of the Identities table on one row?
> 2. Is it hard to center the dialogs based on the actual content area and not the whole screen? Right now they look a little off.

1. The content width is currently set to 1140px. If we increase it 1350px, all columns names will fit.
Screenshot 2023-08-23 103156

2. I'm still looking around, but so far, it seems to be a bit of a problem to actually change the center of the dialog.
There doesn't seem to be a way to attach the dialog to a different container, so we would need to manually calculate its left-right positions. This would also partially break the responsiveness, as the calculations would be made when the dialog is called. If we resized screen after opening the dialog, we would need to reopen it in order to recalculate its left-right positions.
Screenshot 2023-08-23 115728
But I'm still investigating this one.

**Comment by tnotheis** [comment]
> > 1. How wide would you have to make the content area to fit the column names of the Identities table on one row?
> > 2. Is it hard to center the dialogs based on the actual content area and not the whole screen? Right now they look a little off.
> 
> 1. The content width is currently set to 1140px. If we increase it 1350px, all columns names will fit.
>    Screenshot 2023-08-23 103156
> 2. I'm still looking around, but so far, it seems to be a bit of a problem to actually change the center of the dialog.
>    There doesn't seem to be a way to attach the dialog to a different container, so we would need to manually calculate its left-right positions. This would also partially break the responsiveness, as the calculations would be made when the dialog is called. If we resized screen after opening the dialog, we would need to reopen it in order to recalculate its left-right positions.
>    Screenshot 2023-08-23 115728
>    But I'm still investigating this one.

1. Looks good.
2. Hm okay, that's sad. But don't spend too much time on it. It's not that important.

**Review by tnotheis — APPROVED** [review]

**Pull request merged**
