### PR TITLE
Determine the sequence of migrations across different modules

### PR DESCRIPTION
**Pull request by MH321Productions**
# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

### CODE REVIEW

**Comment by daniel-almeida-konkconsulting** [comment]
I have manually tested this, during which process I encountered a specific behavior with the initial migrations, which were not rolled back upon failure.
I've discussed this with @MH321Productions, who mentioned this is in accordance with EF Core's documentation and is expected behavior.
As such, I approve the current changes.

**Review by daniel-almeida-konkconsulting — DISMISSED** [review]

**Review by NikolaDmitrasinovic — DISMISSED** [review]

**Comment by tnotheis** [comment]
> I have manually tested this, during which process I encountered a specific behavior with the initial migrations, which were not rolled back upon failure. I've discussed this with @MH321Productions, who mentioned this is in accordance with EF Core's documentation and is expected behavior. As such, I approve the current changes.

Can you clarify exactly what you mean? Because afaik everything should be rolled back in case of an error.

**Comment by tnotheis** [comment]
@MH321Productions Are you aware of the failing pipelines?

**Comment by MH321Productions** [comment]
> Can you clarify exactly what you mean? Because afaik everything should be rolled back in case of an error.

The documentation states for the `IMigrator.MigrateAsync` method that the latest migration is applied if no target migration is given. A method for clearing the first migration doesn't exist (AFAIK). The only way to entirely clear your DB is, according to the Microsoft docs, to delete all migrations and drop the database.

**Comment by tnotheis** [comment]
> > Can you clarify exactly what you mean? Because afaik everything should be rolled back in case of an error.
> 
> The documentation states for the `IMigrator.MigrateAsync` method that the latest migration is applied if no target migration is given. A method for clearing the first migration doesn't exist (AFAIK). The only way to entirely clear your DB is, according to the Microsoft docs, to delete all migrations and drop the database.

@daniel-almeida-konkconsulting already answered me via DM. I didn't find a way to clear the latest migration either when I implemented the DatabaseMigrator.

**Review by daniel-almeida-konkconsulting — DISMISSED** [review]

**Review by NikolaDmitrasinovic — APPROVED** [review]

**Review by daniel-almeida-konkconsulting — APPROVED** [review]

**Review by tnotheis — APPROVED** [review]

**Pull request merged**
